# Default fallback image
image: alpine:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# Definition of stages
stages:
  - build
  - deploy

stage_build:
  stage: build
  image: node:13.12-buster-slim
  before_script:
    - apt-get update -qq && apt-get install
  only:
    - master
  artifacts:
    paths:
      - dist/
  tags:
    - node 
  script:
    - npm install
    - npm run build

stage_deploy:
  stage: deploy
  image: debian:10.3-slim
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  script:
    - ls -al
    - mv dist web-mpwboard
    - cd web-mpwboard/
    - ls
    - sshpass -V
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o stricthostkeychecking=no -P $DEPLOY_PORT -r $(pwd) $DEPLOY_TARGET

